### ISSUE TITLE
There is still a .terrform.d directory used in $HOME

### ISSUE THREAD

**Issue by notorand-it** [opentofu/opentofu#1727] opened 2024-06-17 07:18 UTC
### OpenTofu Version

```shell
OpenTofu v1.7.2
on linux_amd64
```

### Use Cases

The application still has terraform branding stuff referecned.

### Attempted Solutions

I created a `.tofu.d` and a symlink `.terraform.d` pointing at it.

### Proposal

Any of these:

1. Implement a "tofu" mode with any terraform branding removed and a (default) "terraform" mode with those legacy references and branding still in place.
2. Implement the "Attempted solution"

**Comment by cam72cam** [comment] 2024-06-20 13:05
Closing as a duplicate of https://github.com/opentofu/opentofu/issues/1157

**Closed by cam72cam** 2024-06-20 13:05 UTC
Labels: enhancement, pending-decision
