### ISSUE TITLE
Cognito User Pool: cannot modify or remove schema items

### ISSUE THREAD

**Issue by AreenNser** [opentofu/opentofu#1840] opened 2024-07-22 10:20 UTC
### OpenTofu Version

```shell
OpenTofu v1.7.1
```

### OpenTofu Configuration Files

```
resource "aws_cognito_user_pool" "userpool" {
  provider = aws.curr_account
  name                       = "${var.env}-userpool"
  auto_verified_attributes = ["email"]
  deletion_protection = "INACTIVE" #"ACTIVE"
  email_configuration {
    email_sending_account   = "COGNITO_DEFAULT"
  }

 
  mfa_configuration          = "OFF"
  password_policy {
    minimum_length           = 8
    require_lowercase        = true
    require_numbers          = true
    require_symbols          = true
    require_uppercase        = true
    temporary_password_validity_days = 7
  }
  schema {
    attribute_data_type      = "Number"
    mutable                  = true
    name                     = "id"
    number_attribute_constraints {
      min_value              = "1"
    }
  }
  schema {
    attribute_data_type      = "String"
    mutable                  = true
    name                     = "email"
    required                 = true
    string_attribute_constraints {
      max_length             = "2048"
      min_length             = "0"
    }
  }
  schema {
    attribute_data_type      = "String"
    mutable                  = true
    name                     = "fcm_token"
  }
  schema {
    attribute_data_type      = "String"
    mutable                  = true
    name                     = "first_name"
    string_attribute_constraints {
      min_length             = "1"
    }
  }
  schema {
    attribute_data_type      = "String"
    mutable                  = true
    name                     = "last_name"
    string_attribute_constraints {
      min_length             = "1"
    }
  }
  user_attribute_update_settings {
    attributes_require_verification_before_update = ["email"]
  }
  user_pool_add_ons {
    advanced_security_mode   = "AUDIT"
  }
  username_attributes        = ["email"]
  username_configuration {
    case_sensitive           = false
  }
  verification_message_template {
    default_email_option     = "CONFIRM_WITH_CODE"
  }
  account_recovery_setting {
    recovery_mechanism {
      name     = "verified_email"
      priority = 1
    }

  }
}
```

### Debug Output

```
 # module.cognito_userpool.aws_cognito_user_pool.userpool has changed
  ~ resource "aws_cognito_user_pool" "userpool" {
      + custom_domain             = "auth.stg.test.io"
      + domain                    = "auth.stg.test.io"
        id                        = "us-east-1_xxxxxxxxx"
        name                      = "test-stg-userpool"
      + tags                      = {}
        # (10 unchanged attributes hidden)

      - schema {
          - attribute_data_type = "Number" -> null
          - mutable             = true -> null
          - name                = "id" -> null

          - number_attribute_constraints {
              - min_value = "1" -> null
            }
        }
      - schema {
          - attribute_data_type = "String" -> null
          - mutable             = true -> null
          - name                = "email" -> null
          - required            = true -> null

          - string_attribute_constraints {
              - max_length = "2048" -> null
              - min_length = "0" -> null
            }
        }
      - schema {
          - attribute_data_type = "String" -> null
          - mutable             = true -> null
          - name                = "fcm_token" -> null
        }
      - schema {
          - attribute_data_type = "String" -> null
          - mutable             = true -> null
          - name                = "first_name" -> null

          - string_attribute_constraints {
              - min_length = "1" -> null
            }
        }
      - schema {
          - attribute_data_type = "String" -> null
          - mutable             = true -> null
          - name                = "last_name" -> null

          - string_attribute_constraints {
              - min_length = "1" -> null
            }
        }
      + schema {
          + attribute_data_type      = "Number"
          + developer_only_attribute = false
          + mutable                  = true
          + name                     = "id"
          + required                 = false

          + number_attribute_constraints {
              + min_value = "1"
            }
        }
      + schema {
          + attribute_data_type      = "String"
          + developer_only_attribute = false
          + mutable                  = true
          + name                     = "email"
          + required                 = true

          + string_attribute_constraints {
              + max_length = "2048"
              + min_length = "0"
            }
        }
      + schema {
          + attribute_data_type      = "String"
          + developer_only_attribute = false
          + mutable                  = true
          + name                     = "fcm_token"
          + required                 = false

          + string_attribute_constraints {}
        }
      + schema {
          + attribute_data_type      = "String"
          + developer_only_attribute = false
          + mutable                  = true
          + name                     = "first_name"
          + required                 = false

          + string_attribute_constraints {
              + min_length = "1"
            }
        }
      + schema {
          + attribute_data_type      = "String"
          + developer_only_attribute = false
          + mutable                  = true
          + name                     = "last_name"
          + required                 = false

          + string_attribute_constraints {
              + min_length = "1"
            }
        }

        # (8 unchanged blocks hidden)
    }
```

### Expected Behavior

expected no changes on terraform plan result when there is no changes in schema block.

### Actual Behavior

```
16:06:30   ╷
16:06:30   │ Error: updating Cognito User Pool (us-east-1_fCqOfr0er): cannot modify or remove schema items
16:06:30   │ 
16:06:30   │   with module.cognito_userpool.aws_cognito_user_pool.userpool,
16:06:30   │   on ../../../../modules/cognito_userpool/main.tf line 5, in resource "aws_cognito_user_pool" "userpool":
16:06:30   │    5: resource "aws_cognito_user_pool" "userpool" {
16:06:30   │ 
16:06:30   ╵
```

### Steps to Reproduce

1.tofu init
2.tofu plan
3.tofu apply

### Additional Context

issue: terraform fail on modifying or remove schema items     also if we didn’t change any of them.
fixed by workaround base on https://github.com/hashicorp/terraform-provider-aws/issues/21654 
added 

lifecycle {
  ignore_changes = [
    schema
  ]
}

this will ignore schema changes.. which mean that if we need to edit schema we need to create new cognito… or to make it using UI and add it to the code

### References

https://github.com/hashicorp/terraform-provider-aws/issues/21654

**Comment by assiakhateeb** [comment] 2024-07-22 10:22
+1

**Comment by RLRabinowitz** [comment] 2024-07-22 10:23
Hey @AreenNser thank you for filing this issue!

Which version of the AWS provider are you currently using?

**Comment by AreenNser** [comment] 2024-07-22 10:24
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.59.0"
      configuration_aliases = [aws.curr_account]
    }
  }
}

**Comment by AreenNser** [comment] 2024-07-22 10:24
Hi @RLRabinowitz 
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.59.0"
      configuration_aliases = [aws.curr_account]
    }
  }
}
```

**Comment by RLRabinowitz** [comment] 2024-07-22 13:49
I'll try triaging this soon, as this seems like something that should have been fixed in AWS provider version 5.9.0

**Comment by RLRabinowitz** [comment] 2024-07-22 15:40
Hey I was able to reproduce this issue with the AWS provider, both on the latest AWS provider version, and on 5.9.0.

This seems to be an AWS provider related issue. There are new issues open for the provider that are related to the issue - https://github.com/hashicorp/terraform-provider-aws/issues/38224 and https://github.com/hashicorp/terraform-provider-aws/issues/38096.

Please discuss the issue on the AWS provider repository

**Closed by RLRabinowitz** 2024-07-22 15:40 UTC
Labels: bug, pending-decision

**Comment by AreenNser** [comment] 2024-07-23 06:40
Thanks @RLRabinowitz

**Comment by bannarisoftwares** [comment] 2024-08-26 02:23
Hi @AreenNser 

Add 
```
string_attribute_constraints {
      max_length = "2048"
      min_length = "0"
    }
 ```
on each `schema` to avoid this issue

Example:

```
schema {
    name                = "scope"
    attribute_data_type = "String"
    mutable             = true
    required            = false
    string_attribute_constraints {
      max_length = "2048"
      min_length = "0"
    }
  }
  
  ```

> When defining an attribute_data_type of String or Number, the respective attribute constraints configuration block (e.g string_attribute_constraints or number_attribute_constraints) is required to prevent recreation of the Terraform resource. This requirement is true for both standard (e.g., name, email) and custom schema attributes.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#schema
