### ISSUE TITLE
Agregate modules as separate stateful components

### ISSUE THREAD

**Issue by paulaustin-automutatio** [opentofu/opentofu#1817] opened 2024-07-12 23:02 UTC
### OpenTofu Version

```shell
OpenTofu v1.7.2
on windows_amd64
```

### Use Cases

It is often desirable to separate the components of an application environment into modules that can be deployed independently of each other. For example the database resources change infrequently, likely only on a db version upgrade. Where as the web app is updated on every change. Some times you'll need to add or remove components, for example add a new db for an upgrade migrate the services to that db, then remove the old db. This is all in the same environment, but different components.

All of these components (module + configuration) can be done by having separate modules and state files for each. However there is no way to have an aggregate module that could be used to see what an overall plan (or apply) is across all those modules.

### Attempted Solutions

terragrunt or custom solutions

### Proposal

Implement a mechanism where one or more self contained module folder can be included in a module as a "dependency". By self contained I mean that you can't pass variables to that module. The reason for this is so that you can run those modules independently from the aggregator.

dependent_modules {
 sources =["./Db", "./Web"]
}

**Comment by cam72cam** [comment] 2024-07-26 14:03
Closing this as duplicate of #931

**Closed by cam72cam** 2024-07-26 14:03 UTC
Labels: enhancement, pending-decision
