### ISSUE TITLE
Support the XDG Base Directory Specification

### ISSUE THREAD

**Issue by offsetcyan** [opentofu/opentofu#303] opened 2023-08-28 20:17 UTC
Currently, OpenTofu will default to storing a data in the user's home directory, i.e. `~/.opentofu.d` (could still be `~/.terraform.d`). The correct way to store cache, config and state on a user's machine is to follow a platform's best practices - in Linux's case most Linux desktops support and/or adhere to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), a specification for environment variables and default storage locations for certain types of data a program might want to store in dotfiles. Following this spec would allow Linux and MacOS users the ability to specify correct directories for their environment. 

(Note: MacOS by default doesn't follow the XDG spec - they have [their own](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1), however it doesn't refer to environment variables (i.e. supporting MacOS's standard is a separate issue.))

**Comment by grxnola** [comment] 2023-09-20 16:07
I've updated the issue with an OpenTofu specific description of the issue.

**Comment by Tony-Sol** [comment] 2023-12-04 23:47
Since hc ignores this, i really hope XDG Spec support support will be added in tofu

**Comment by cube2222** [comment] 2024-01-18 13:24
Accepted and open for contribution. Please make sure to implement this as an optional feature, in a fully backward-compatible manner.

**Comment by cam72cam** [comment] 2024-01-18 16:23
I'm also taking a look and am a bit confused.  config_unix.go is missing the XDG_DATA_HOME check, and internal/command/command.go:DefaultPluginVendorDir never has a prefix appended.  I'm wondering if this is even functional.

**Comment by cam72cam** [comment] 2024-01-18 16:29
Near as I can tell, the code was rewritten over time and the XDG_DATA_HOME spec was not included.  The documentation however was not updated.  @avorima I'll assign this to you as you've got a draft ready.

**Comment by avorima** [comment] 2024-01-18 16:38
I will include XDG_DATA_HOME for plugins in my draft open a PR. The fallback will still be ~/.terraform.d

**Comment by offsetcyan** [comment] 2024-01-19 10:49
Shouldn't `~/.config` be used in the case XDG_CONFIG_HOME is not defined according to the specification? Afaict for correct behaviour, if neither `XDG_CONFIG_HOME/opentofu` or `~/.terraform.d` exist, the directory that should be created is `$HOME/config/opentofu`.

**Comment by avorima** [comment] 2024-01-19 11:21
I think you're right. I was trying to make the XDG support as opt-in as possible, but if `~/.terraform.d` doesn't exist then XDG should be the default.

So the lookup order would be:
- use `~/.terraform.d` if it exists
- use `$XDG_CONFIG_HOME/opentofu` if it is set
- use `~/.config`

Same with `$XDG_DATA_HOME/opentofu` and `~/.local/share/opentofu`

**Comment by rpdelaney** [comment] 2024-01-22 15:20
I would think that conforming to the spec means non-conforming behavior would be the fallback, not the other way round:
```
if $XDG_CONFIG_HOME/opentofu/ exists:
    use that
else if ~/.config/opentofu/ exists
    use that
else if ~/.terraform.d/ exists
    use that
```

**Comment by cam72cam** [comment] 2024-01-22 15:58
Part of the problem is that we don't want to break existing setups, that's why the directory is still ~/.terraform.d at the moment instead of ~/.opentofu.d.

Users might have XDG_CONFIG_HOME as part of their .shellrc and suddenly be confused why their config is not working as expected.

I think we have to:
1. Use `~/.terraform.d` if it exists
2. `$XDG_CONFIG_HOME/opentofu/` if $XDG_CONFIG_HOME is set
3. ~/.config/opentofu/ if none of the above are available.

As far as XDG_DATA_HOME for the plugin search path, I don't see why we couldn't search in all 3 locations?

**Comment by avorima** [comment] 2024-01-22 17:03
I think we can optimize to only search all 3 locations if XDG_DATA_HOME has a different value than empty or ~/.local/share. Otherwise use 2.

**Comment by rpdelaney** [comment] 2024-01-22 19:35
> Part of the problem is that we don't want to break existing setups

I agree! That's why we should use existing configurations if they are found. We need not hinge anything in the flow control on whether XDG_CONFIG_HOME is set, because what really matters is whether the configuration files can be found, and where. 

Following the pseudocode in my previous comment in the scenario where the user has their configuration at `~/.terraform.d/`, we would check for `~/.config/opentofu/` and not finding it we would fall back with success to the home directory. Therefore, nobody would have their configuration break when upgrading.

**Comment by cube2222** [comment] 2024-01-23 14:48
As I've mentioned previously

> Accepted and open for contribution. Please make sure to implement this as an optional feature, in a fully backward-compatible manner.

the goal here, as the issue is accepted now, is to support XDG environment variables for users that set them (or find the config wherever it is) but not make **any** changes for other users.

Which means the behaviour should be
1. Use ~/.terraform.d if it exists
2. Otherwise, if XDG_CONFIG_HOME is present, use that.
3. Otherwise, fall back to ~/.terraform.d

I understand that this is not making OpenTofu fully adhere to the spec. It's a compromise to satisfy the workflow of people who opt into it by setting the relevant env vars, and not introducing any risk of breakage for others (existing tooling may operate on ~/.terraform.d and expect to find the config there).

**Comment by rpdelaney** [comment] 2024-01-23 19:21
> the goal here, as the issue is accepted now, is to support XDG environment variables for users that set them (or find the config wherever it is) but not make any changes for other users.

I can't emphasize my agreement with this enough. I completely agree that not disrupting existing users' workflows is essential. 

To clarify my earlier proposal:

- The order of checking directories (first XDG, then ~/.terraform.d) is primarily for new installations. It ensures adherence to XDG for newcomers while also guaranteeing that configurations in ~/.terraform.d remain unaffected.

- For existing users, the presence of ~/.terraform.d means their current setup works as usual. The difference in my proposal would only affect new users or environments without existing configurations.

I understand this is a nuanced topic and am open to other approaches. It's not a crucial issue for me, so I won't push further on this.

**Comment by avorima** [comment] 2024-01-26 16:13
Sorry, I closed my draft PR by accident but re-opened it at https://github.com/opentofu/opentofu/pull/1200.

I think it fulfills all requirements that were mentioned here.

**Comment by mikelolasagasti** [comment] 2024-01-29 09:53
In https://github.com/opentofu/opentofu/issues/1195 I wrote mi findings on how OpenTofu has two different systems for home directory detection in the code, but I've been asked to move the discussion to this issue.

The current options are:

- Using `github.com/mitchellh/go-homedir`
- Using custom code in `internal/command/cliconfig/config_unix.go` and `internal/command/cliconfig/config_windows.go`

[The PR attached to this issue](https://github.com/opentofu/opentofu/pull/1200) that adds XDG support is based and extends the second approach.

There are several issues with current status:

- `github.com/mitchellh/go-homedir` is a library just to detect $home dirs, doesn't have any XDG logic on top.
- Custom code in [internal/command/cliconfig/config_windows.go](https://github.com/opentofu/opentofu/blob/main/internal/command/cliconfig/config_windows.go#L43-L53) to detect `$home` in Windows enviroments is using deprectated functions.
- Custom code in [internal/command/cliconfig/config_unix.go](https://github.com/opentofu/opentofu/blob/main/internal/command/cliconfig/config_unix.go#L37-L59) to detect `$home` in Linux.

There is a library `https://github.com/adrg/xdg` that could be used to remove the usage of `github.com/mitchellh/go-homedir` and custom code in `config_unix.go` and `config_windows.go`.

The PR addressing this issue, adding XDG spec support, is great idea and PR looks good. The issue is should the PR use `https://github.com/adrg/xdg` and touch other parts of the code or should that be done after the PR is merged?

**Comment by cube2222** [comment] 2024-01-29 13:55
@mikelolasagasti If I understand correctly, switching to the xdg library would also change the default fallback to the likes of `~/.config`, while the goal here is to only change behaviour of OpenTofu if XDG flags are detected, as described in https://github.com/opentofu/opentofu/issues/303#issuecomment-1906209913

I might be missing something, though.

**Closed** 2024-01-31 10:04 UTC
Labels: good first issue, help wanted, accepted

**Comment by offsetcyan** [comment] 2024-02-07 02:25
So if $XDG_CONFIG_HOME isn't set (i.e. most machines) OpenTofu will still dump `.tofurc` in $HOME?

**Comment by cube2222** [comment] 2024-02-07 16:35
@offsetcyan Yup, exactly.

**Comment by offsetcyan** [comment] 2024-02-07 16:55
Awesome patch and nice to see the community-driven approach of OpenTofu functioning as intended!
