### ISSUE TITLE
S3 remote backend without DynamoDB

### ISSUE THREAD

**Issue by stevehipwell** [opentofu/opentofu#1938] opened 2024-08-22 09:49 UTC
### OpenTofu Version

```shell
OpenTofu v1.8.1
```

### Use Cases

I'd like to be able to use a S3 remote backend without requiring DynamoDB to handle the state locking. This should now be possible given the [announcement](https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-s3-conditional-writes/) that S3 now supports conditional writes.

### Attempted Solutions

n/a

### Proposal

OpenTofu should support locking the remote state directly on S3 if DynamoDB isn't configured via the `if-none-match` header.

**Comment by stevehipwell** [comment] 2024-08-22 09:51
I also created https://github.com/hashicorp/terraform/issues/35625 to track this on the other side of the wall.

**Comment by ollevche** [comment] 2024-08-22 09:55
Hey @stevehipwell, thank you for this issue! The core team regularly reviews new issues and discusses them, but this can take a little time. Please bear with us while we get to your issue. If you're interested, the contribution guide has a section about the [decision-making process](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#who-decides-if-a-feature-will-be-implemented-and-how-is-that-decision-made).

**Comment by cam72cam** [comment] 2024-08-22 10:54
Hi @stevehipwell, this is a duplicate of an existing issue: https://github.com/opentofu/opentofu/issues/599.  Please add this to the conversation there.

**Closed by cam72cam** 2024-08-22 10:54 UTC
Labels: enhancement, pending-decision
