### ISSUE TITLE
Variable Use in Module Source field.

### ISSUE THREAD

**Issue by coreydeli** [opentofu/opentofu#1589] opened 2024-04-30 19:48 UTC
### OpenTofu Version

```shell
1.7.0
```

### Use Cases

This feature would allow use of multi-tanancy solutions as we scale from Dev to Prod.

Case in point, in a dev environment a change may occur that could negatively affect prod. It is made on the Dev Branch. Dev gets tested and then merged into the QA/Staging Branch where additional testing is done. This would then inherit the flags for the version to reference from CI platforms like GitHub.

Upon ensuring the system works properly the branch would be merged to the production branch/tag which would easily inherit the change without the need to constantly change the `?ref=` field to the branches you want for each test.

### Attempted Solutions

Source = GitHub.com/your-repo?ref=${var.branch}

Or

Source = GitHub.com/your-repo?ref=${local.branch}

**Comment by cam72cam** [comment] 2024-05-01 11:14
Hi @coreydeli, this is a duplicate of #286, which is being worked on under #1042. Please vote on and comment on those other issues!

**Closed by cam72cam** 2024-05-01 11:14 UTC
Labels: enhancement, pending-decision
