### ISSUE TITLE
`import` block might cause a destroy action to attempt destruction of an already-destroyed resource

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1803] opened 2024-07-11 14:41 UTC
### OpenTofu Version

```shell
1.8.0-beta
```

### OpenTofu Configuration Files

```hcl
resource "random_integer" "a" {
  max = 10
  min = 1
}

import {
  to = random_integer.a
  id = "3,1,10"
}

resource "random_integer" "b" {
  max = 10
  min = 1
}

import {
  to = random_integer.b
  id = "5,1,10"
}
```

### Debug Output

.

### Expected Behavior

When attempting to destroy the configuration, after `random_integer.a` has been destroyed as part of a targeted destroy, OpenTofu should attempt to only destroy `random_integer.b`

### Actual Behavior

OpenTofu attempts to destroy both `random_integer.a` and `random_integer.b`

The logs you get from the `tofu destroy` action:
```
random_integer.a: Preparing import... [id=3,1,10]
random_integer.a: Refreshing state... [id=3]
random_integer.b: Refreshing state... [id=5]

OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

OpenTofu will perform the following actions:

  # random_integer.a will be destroyed
  - resource "random_integer" "a" {
      - id     = "3" -> null
      - max    = 10 -> null
      - min    = 1 -> null
      - result = 3 -> null
    }

  # random_integer.b will be destroyed
  - resource "random_integer" "b" {
      - id     = "5" -> null
      - max    = 10 -> null
      - min    = 1 -> null
      - result = 5 -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.
```

It should only attempt to destroy `random_integer.b`

### Steps to Reproduce

1. `tofu init`
2. `tofu apply`
3. `tofu destroy -target=random_integer.a`
4. `tofu destroy`

### References

- Relevant issue in the Terraform Repository - https://github.com/hashicorp/terraform/issues/35151

**Comment by tony21921** [comment] 2024-08-06 02:42
I am working on this and will submit a PR

**Comment by nayang7** [comment] 2024-08-13 02:36
> I am working on this and will submit a PR

going to submit a PR, Co-authored-by: @tony21921

**Comment by apparentlymart** [comment] 2024-11-06 23:00
I would perhaps describe this problem a little differently: `tofu destroy` _in particular_ should not pay any attention to `import` blocks at all, and should instead focus only on generating "delete" actions for any resource instance objects already tracked in the prior state. 

The `tofu destroy` command is essentially a shorthand for `terraform apply -destroy`, telling OpenTofu to create a plan in the "destroy" [planning mode](https://opentofu.org/docs/cli/commands/plan/#planning-modes). The planning mode causes the language runtime's "Plan" operation to divert into one of three codepaths:

https://github.com/opentofu/opentofu/blob/d396502d280d6946c2c6ea8aaa06046e36baf231/internal/tofu/context_plan.go#L211-L220

The destroy mode in particular has an interesting quirk: it actually internally runs _two_ plan phases, with the first in "normal" mode to make sure that the prior state represents the remote system as closely as possible, except that it sneakily sets the `PreDestroyRefresh` field in the planning options when creating that plan:

https://github.com/opentofu/opentofu/blob/d396502d280d6946c2c6ea8aaa06046e36baf231/internal/tofu/context_plan.go#L399-L449

If that succeeds, it then performs the "real" destroy-mode plan phase (with `opts` here still carrying the caller's request to plan in destroy mode):

https://github.com/opentofu/opentofu/blob/d396502d280d6946c2c6ea8aaa06046e36baf231/internal/tofu/context_plan.go#L451-L458

The main handling of the planning mode happens during graph construction:

https://github.com/opentofu/opentofu/blob/d396502d280d6946c2c6ea8aaa06046e36baf231/internal/tofu/context_plan.go#L840-L893

From reading the trace logs I've confirmed that the import is happening during that secret initial "normal mode" plan, when it visits the `NodePlannableResourceInstance` representing `random_integer.a`:

```
[TRACE] vertex "random_integer.a": starting visit (*tofu.NodePlannableResourceInstance)
[TRACE] Resolving provider key for random_integer.a
[TRACE] Resolved provider key for random_integer.a as %!s(<nil>)
[TRACE] tofu.contextPlugins: Serving provider "registry.opentofu.org/hashicorp/random" schema from global schema cache
[TRACE] GRPCProvider: ImportResourceState
[TRACE] GRPCProvider: GetProviderSchema
[TRACE] GRPCProvider: GetProviderSchema: serving from global schema cache: address=registry.opentofu.org/hashicorp/random
[TRACE] graphNodeImportState: import random_integer.a "3,1,10" produced instance object of type random_integer
[TRACE] NodeAbstractResourceInstance.refresh for random_integer.a
[TRACE] tofu.contextPlugins: Serving provider "registry.opentofu.org/hashicorp/random" schema from global schema cache
[TRACE] tofu.contextPlugins: Serving provider "registry.opentofu.org/hashicorp/random" schema from global schema cache
[TRACE] GRPCProvider: ReadResource
```

Therefore it seems like probably the least invasive change would be to make the `PlanGraphBuilder` use its existing `preDestroyRefresh` flag also to set an additional flag on the concrete `nodeExpandPlannableResource` objects it creates which tells them that any import blocks ought to be ignored:

https://github.com/opentofu/opentofu/blob/d396502d280d6946c2c6ea8aaa06046e36baf231/internal/tofu/graph_builder_plan.go#L271-L279

The expansion node can then in turn skip resolving imports when its own "skip imports" flag is set:

https://github.com/opentofu/opentofu/blob/d396502d280d6946c2c6ea8aaa06046e36baf231/internal/tofu/node_resource_plan.go#L329-L377

---

In an ideal world we wouldn't have this secret "normal-ish plan" hidden inside the destroy plan implementation with various little special cases attached to it, but it's risky to replace it because the destroy plan implementation is very focused _only_ on the problem of generating "destroy" actions for objects in the state and so doesn't really know how to deal with anything else.

**Comment by Evi1Pumpkin** [comment] 2024-11-22 22:58
I followed your approach, @apparentlymart. Thanks for your help! 
I made a few simple changes. Instead of skipping the resolved import in `resourceInstanceSubgraph()`, I decided to skip the expansion and resolution logic of the `import` block targets altogether in an earlier phase.

Let me know if you have a different opinion.

**Closed** 2024-11-25 21:52 UTC
Labels: bug, accepted
