### ISSUE TITLE
Allow plan when prevent_destroy is true

### ISSUE THREAD

**Issue by jgournet** [opentofu/opentofu#1299] opened 2024-02-23 00:09 UTC
### OpenTofu Version

```shell
1.6.2
```

### Use Cases

Currently, as soon as a resource specifies:
```
  lifecycle {
    prevent_destroy = true
  }
```
planning against will fail right away

### Attempted Solutions

technically, we can modify the module to remove the prevent_destroy so we can see the plan (and why opentofu wants to destroy that resource and/or be able to pass a "-target" argument for other resources), but it defeats the purpose of having "prevent_destroy" as now we may make the mistake of applying this.

### Proposal

Instead of failing during plan, opentofu should say something like:
"this resource should be destroyed but prevent_destroy will prevent it".

So running an apply on this would apply everything else but this resource.

**Comment by RLRabinowitz** [comment] 2024-02-26 08:25
Hey @jgournet , thank you for your submission!

I think that this issue is a duplicate of https://github.com/opentofu/opentofu/issues/1027, which states that `prevent_destroy` should fail **after** the plan has been created, so that you could easily figure out why the resource had to be destroyed.

The fix is already merged, and will be released in 1.7.0.

I'm closing the issue, if the issue I've referenced here is not exactly your use-case here, feel free to re-open the issue and explain your use-case further.

**Closed by RLRabinowitz** 2024-02-26 08:25 UTC
Labels: enhancement, pending-decision
