### ISSUE TITLE
Incorrect Test Data in internal/states/statefile/testdata/roundtrip

### ISSUE THREAD

**Issue by eduzgun** [opentofu/opentofu#1713] opened 2024-06-10 08:36 UTC
### OpenTofu Version

```shell
OpenTofu v1.6.2
on windows_amd64
```

### OpenTofu Configuration Files

N/A
Just running tests

### Debug Output

![image](https://github.com/opentofu/opentofu/assets/100037959/497e92de-fbfa-4e59-9aad-7c5763f6b64f)

### Expected Behavior

Contents of all tfstate data in in `internal/states/statefile/testdata/roundtrip` should be JSON. For example it should look like this:

https://github.com/opentofu/opentofu/blob/b084b3e3f42839c8d285f795ffb682634f461228/internal/states/statefile/testdata/roundtrip/v4-simple.in.tfstate#L1

### Actual Behavior

These files don't contain a tfstate JSON object and just have the name followed by "in.tfstate"

- https://github.com/opentofu/opentofu/blob/b084b3e3f42839c8d285f795ffb682634f461228/internal/states/statefile/testdata/roundtrip/v4-modules.out.tfstate#L1
- https://github.com/opentofu/opentofu/blob/b084b3e3f42839c8d285f795ffb682634f461228/internal/states/statefile/testdata/roundtrip/v4-future.out.tfstate#L1
- https://github.com/opentofu/opentofu/blob/b084b3e3f42839c8d285f795ffb682634f461228/internal/states/statefile/testdata/roundtrip/v4-foreach.out.tfstate#L1
- https://github.com/opentofu/opentofu/blob/b084b3e3f42839c8d285f795ffb682634f461228/internal/states/statefile/testdata/roundtrip/v4-simple.out.tfstate#L1

### Steps to Reproduce

`go test ./internal/states/statefile`

### Additional Context

Ran into this while trying to fix tests on Windows.
Also see a file named version 1 but it uses version 4:
https://github.com/opentofu/opentofu/blob/b084b3e3f42839c8d285f795ffb682634f461228/internal/states/statefile/testdata/roundtrip/v1-simple.out.tfstate#L1

The testdata is used by this function 
https://github.com/opentofu/opentofu/blob/b084b3e3f42839c8d285f795ffb682634f461228/internal/states/statefile/roundtrip_test.go#L21

### References

#1201

**Comment by cam72cam** [comment] 2024-06-10 11:22
Ah I see you are on windows, that's the problem.

This is a duplicate of https://github.com/opentofu/opentofu/issues/1201.  A lot of tests are broken due to windows pathing issues.  Feel free to submit a PR under #1201 if you want to try to fix this.

**Closed by cam72cam** 2024-06-10 11:22 UTC
Labels: bug, pending-decision

**Comment by cam72cam** [comment] 2024-06-10 15:15
Any help here is appreciated!
