### ISSUE TITLE
local-exec: ssh to another Server hangs

### ISSUE THREAD

**Issue by kszyma** [opentofu/opentofu#1301] opened 2024-02-23 11:30 UTC
### OpenTofu Version

```shell
OpenTofu v1.6.2
on linux_amd64
+ provider registry.opentofu.org/hashicorp/null v3.2.2
+ provider registry.opentofu.org/hashicorp/vsphere v2.6.1
```

### OpenTofu Configuration Files

```hcl
  provisioner "remote-exec" {
    inline = [
      "ssh -i /root/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -vvv -o ControlMaster=no -o StrictHostKeyChecking=no testuser@testserver whoami",
    ]

    connection {
      type        = "ssh"
      user        = "root"
      private_key = file("${path.module}/data/ssh/id_rsa")
      host        = each.value.ip
    }
  }
  ````

### Debug Output

```
module.dev_vms.vsphere_virtual_machine.vm["0"]: Destroying... [id=xxxxxxxx-6818-e78f-74f3-bf0ef8492174]
module.dev_vms.vsphere_virtual_machine.vm["0"]: Destruction complete after 4s
module.dev_vms.vsphere_virtual_machine.vm["0"]: Creating...
module.dev_vms.vsphere_virtual_machine.vm["0"]: Still creating... [10s elapsed]
module.dev_vms.vsphere_virtual_machine.vm["0"]: Still creating... [20s elapsed]
module.dev_vms.vsphere_virtual_machine.vm["0"]: Still creating... [...]
module.dev_vms.vsphere_virtual_machine.vm["0"]: Provisioning with 'remote-exec'...
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): Connecting to remote host via SSH...
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec):   Host: 1.2.3.4
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec):   User: root
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec):   Password: false
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec):   Private key: true
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec):   Certificate: false
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec):   SSH Agent: true
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec):   Checking Host Key: false
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec):   Target Platform: unix
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): Connected!
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): OpenSSH_8.9p1 Ubuntu-3ubuntu0.6, OpenSSL 3.0.2 15 Mar 2022
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: Reading configuration data /etc/ssh/ssh_config
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: /etc/ssh/ssh_config line 21: Applying options for *
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: resolving "testserver" port 22
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug3: resolve_host: lookup testserver:22
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug3: ssh_connect_direct: entering
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: Connecting to testserver [1.2.3.5] port 22.
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug3: set_sock_tos: set socket 3 IP_TOS 0x10
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: Connection established.
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: identity file /root/.ssh/id_rsa type 0
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: identity file /root/.ssh/id_rsa-cert type -1
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9p1 Debian-10+deb10u4
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: compat_banner: match: OpenSSH_7.9p1 Debian-10+deb10u4 pat OpenSSH* compat 0x04000000
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: fd 3 setting O_NONBLOCK
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: Authenticating to testserver:22 as 'testuser'
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug3: order_hostkeyalgs: no algorithms matched; accept original
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug3: send packet: type 20
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: SSH2_MSG_KEXINIT sent
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug3: receive packet: type 20
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: SSH2_MSG_KEXINIT received
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: local client KEXINIT proposal
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c,kex-strict-c-v00@openssh.com
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: compression ctos: none,zlib@openssh.com,zlib
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: compression stoc: none,zlib@openssh.com,zlib
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: languages ctos:
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: languages stoc:
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: first_kex_follows 0
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: reserved 0
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: peer server KEXINIT proposal
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,kex-strict-s-v00@openssh.com
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: compression ctos: none,zlib@openssh.com
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: compression stoc: none,zlib@openssh.com
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: languages ctos:
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: languages stoc:
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: first_kex_follows 0
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: reserved 0
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug3: kex_choose_conf: will use strict KEX ordering
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: kex: algorithm: curve25519-sha256
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: kex: host key algorithm: ssh-ed25519
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug3: send packet: type 30
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug3: receive packet: type 31
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: SSH2_MSG_KEX_ECDH_REPLY received
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: Server host key: ssh-ed25519 SHA256:mhYYgxJvMygSCoRyIZIzkm/1f7DCYQGMt0VtGcJugvw
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): Warning: Permanently added 'testserver' (ED25519) to the list of known hosts.
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug3: send packet: type 21
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: ssh_packet_send2_wrapped: resetting send seqnr 3
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: ssh_set_newkeys: mode 1
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: rekey out after 134217728 blocks
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: SSH2_MSG_NEWKEYS sent
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: expecting SSH2_MSG_NEWKEYS
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug3: receive packet: type 21
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: ssh_packet_read_poll2: resetting read seqnr 3
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: SSH2_MSG_NEWKEYS received
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: ssh_set_newkeys: mode 0
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: rekey in after 134217728 blocks
module.dev_vms.vsphere_virtual_machine.vm["0"]: Still creating... [3m0s elapsed]
module.dev_vms.vsphere_virtual_machine.vm["0"]: Still creating... [3m10s elapsed]
module.dev_vms.vsphere_virtual_machine.vm["0"]: Still creating... [3m20s elapsed]
module.dev_vms.vsphere_virtual_machine.vm["0"]: Still creating... [Here it hangs endless until ctrl-c]
```

### Expected Behavior

Execute whoami

### Actual Behavior

Hangs

### Steps to Reproduce

1. tofu apply

### Additional Context

When i do

```
ssh -i /root/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -vvv -o ControlMaster=no -o StrictHostKeyChecking=no testuser@testserver whoami
```

by hand everything works.

**Comment by janosdebugs** [comment] 2024-02-23 11:34
Hi @kszyma am I understanding correctly that you want to use a jump host to then SSH again to another host? If so, could you please run the inline SSH in verbose mode?

**Comment by kszyma** [comment] 2024-02-23 11:36
I did a -vvv. Did you mean this ?

**Comment by kszyma** [comment] 2024-02-23 11:38
Ah..maybe TF_LOG to debug ? :)

**Comment by kszyma** [comment] 2024-02-23 11:42
The last Lines are still

```
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug2: ssh_set_newkeys: mode 0
module.dev_vms.vsphere_virtual_machine.vm["0"] (remote-exec): debug1: rekey in after 134217728 blocks
```

also with ```export TF_LOG=DEBUG```

**Comment by janosdebugs** [comment] 2024-02-23 12:07
Can you `strace` the SSH command on the jump host?

**Comment by cam72cam** [comment] 2024-05-21 16:43
Closing as not able to reproduce.

**Closed by cam72cam** 2024-05-21 16:43 UTC
Labels: bug, pending-decision
