### ISSUE TITLE
Mock_data/Override_data Type Validation Error

### ISSUE THREAD

**Issue by miles-qarik** [opentofu/opentofu#2200] opened 2024-11-21 21:57 UTC
### OpenTofu Version

```shell
v1.8.2
v1.8.5
v1.9.0-alpha2
```

### OpenTofu Configuration Files

# Bare minimum info needed to replicate issue
```hcl
variable "false" {
  default = false
}

data "google_compute_networks" "all_networks" {
  project  = "my-networks-project"
}

```
# This is my tftest.hcl file
```
mock_provider "google" {}

override_data {
    target = data.google_compute_networks.all_networks
    values = {
        networks = ["this-network", "that-network", "deez-networks"]
    }
}
run "demo" {
  assert {
    condition     = var.false == true
    error_message = "Debugging peer_networks: ${jsonencode(data.google_compute_networks.all_networks)}"
  }
}
```

### Debug Output

https://gist.github.com/miles-qarik/ecd2fba9327cdaeb1ccac48f0406c78d

### Expected Behavior

Networks value should have been updated and output correctly as it is receiving a valid list of strings

### Actual Behavior

```
│ Warning: Ignored mock/override field `networks`
│ 
│   with data.google_compute_networks.all_networks,
│   on main.tf line 5, in data "google_compute_networks" "all_networks":
│    5: data "google_compute_networks" "all_networks" {
│ 
│ Values provided for override / mock must match resource fields types: list of string required, but received tuple.
```

### Steps to Reproduce

1. tofu init
2. tofu test

### References

Similar behavior in #2140, #2139, #2038

**Comment by ollevche** [comment] 2024-11-22 11:32
Yep, this is same root cause as in the linked issues so the fix will be released soon.

**Comment by cam72cam** [comment] 2024-11-25 12:11
Closing as the release has happened.

**Closed by cam72cam** 2024-11-25 12:11 UTC
Labels: bug, pending-decision
