### ISSUE TITLE
`tofu test` - Fails to init when test has spaces in its name

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1358] opened 2024-03-11 10:19 UTC
### OpenTofu Version

```shell
1.6.2
```

### OpenTofu Configuration Files

You should have a `module` folder with some tf configuration, and also have tf configuration in the current folder

Then, have `main.tftest.hcl` be:
```hcl
run "it fails" {
  command = plan
  module {
    source = "./module"
  }
}
```

### Debug Output

.

### Expected Behavior

`tofu init` does not fail

### Actual Behavior

`tofu init` fails:

```
╷
│ Error: Module not installed
│ 
│   on main.tftest.hcl line 3, in run "it fails":
│    3:   module {
│ 
│ This module is not yet installed. Run "tofu init" to install all modules required by this configuration.
╵
```

### Steps to Reproduce

1. `tofu init`

### References

Related issue in the Terraform repository - https://github.com/hashicorp/terraform/issues/34372

**Comment by sanskruti-shahu** [comment] 2024-03-12 11:55
As discussed in a related issue on Terraform's repository [here](https://github.com/hashicorp/terraform/issues/34372#issuecomment-1875279150), it has been discussed that including spaces in a run block name is not valid due to the nature of HCL identifiers. So, it would be beneficial to implement an error message related to invalid run block name. So, Is this the expected behavior or should we anticipate something different? Please provide clarification.

**Comment by RLRabinowitz** [comment] 2024-03-12 15:13
Yes we should provide a similar error there

```
│ Error: Invalid run block name
│ 
│   on main.tftest.hcl line 1, in run "it fails":
│    1: run "it fails" {
│ 
│ A name must start with a letter or underscore and may contain only letters, digits, underscores, and dashes.
```

**Comment by sanskruti-shahu** [comment] 2024-03-12 15:50
Ok got it. I would be happy to work on this issue.

**Comment by sanskruti-shahu** [comment] 2024-03-12 15:51
Ok got it. Could you assign it to me, I would be happy to work on this issue.

**Closed** 2024-04-25 15:11 UTC
Labels: bug, help wanted, accepted
