### ISSUE TITLE
`templatefile` crashes when path to file is sensitive

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1802] opened 2024-07-11 14:34 UTC
### OpenTofu Version

```shell
1.8.0-beta
```

### OpenTofu Configuration Files

main.tf:
```hcl
variable "file" {
  sensitive = true
}

resource "null_resource" "a" {
  triggers = {
    value = templatefile(var.file, {})
  }
}
```

### Debug Output

.

### Expected Behavior

Should not crash. For compatibility reasons - the trigger should be sensitive

### Actual Behavior

Crash:

```
Planning failed. OpenTofu encountered an error while generating this plan.

╷
│ Error: Error in function call
│ 
│   on main.tf line 7, in resource "null_resource" "a":
│    7:     value = templatefile(var.file, {})
│     ├────────────────
│     │ while calling templatefile(path, vars)
│ 
│ Call to function "templatefile" failed: panic in function implementation: value is marked, so must be unmarked first
│ goroutine 90 [running]:
│ runtime/debug.Stack()
│       ~/sdk/go1.21.4/src/runtime/debug/stack.go:24 +0x64
│ github.com/zclconf/go-cty/cty/function.errorForPanic({0x10449cfe0, 0x104abea30})
│       ~/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/function/error.go:44 +0x28
│ github.com/zclconf/go-cty/cty/function.Function.returnTypeForValues.func1()
│       ~/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/function/function.go:226 +0x94
│ panic({0x10449cfe0?, 0x104abea30?})
│       ~/sdk/go1.21.4/src/runtime/panic.go:920 +0x254
│ github.com/zclconf/go-cty/cty.Value.assertUnmarked({{{0x104afde98, 0x140001aefd9}}, {0x1047475c0, 0x14000d09fb0}})
│       ~/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/marks.go:141 +0x58
│ github.com/zclconf/go-cty/cty.Value.AsString({{{0x104afde98, 0x140001aefd9}}, {0x1047475c0, 0x14000d09fb0}})
│       ~/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/value_ops.go:1385 +0x40
│ github.com/opentofu/opentofu/internal/lang/funcs.makeTemplateFileFuncImpl.func1({0x1400015c598, 0x7}, 0x14000d385d0)
│       ~/Projects/opentf/internal/lang/funcs/filesystem.go:154 +0x29c
│ github.com/opentofu/opentofu/internal/lang/funcs.makeTemplateFileFuncImpl.func3({0x140009fee80, 0x2, 0x2})
│       ~/Projects/opentf/internal/lang/funcs/filesystem.go:188 +0x1cc
│ github.com/zclconf/go-cty/cty/function.Function.returnTypeForValues({0x140009fc460}, {0x140009fee80, 0x2, 0x2})
│       ~/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/function/function.go:230 +0x92c
│ github.com/zclconf/go-cty/cty/function.Function.Call({0x140009fc460}, {0x140009fee80, 0x2, 0x2})
│       ~/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/function/function.go:250 +0x68
│ github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0x140006601e0, 0x14000d09e78)
│       ~/go/pkg/mod/github.com/opentofu/hcl/v2@v2.0.0-20240416130056-03228b26f391/hclsyntax/expression.go:528 +0x4240
│ github.com/hashicorp/hcl/v2/hclsyntax.(*ObjectConsExpr).Value(0x140006dcaa0, 0x14000d09e78)
│       ~/go/pkg/mod/github.com/opentofu/hcl/v2@v2.0.0-20240416130056-03228b26f391/hclsyntax/expression.go:1210 +0x314
│ github.com/hashicorp/hcl/v2/hcldec.(*AttrSpec).decode(0x14000bbafc0, 0x1400010f620, {0x0, 0x0, 0x0}, 0x14000d09e78)
│       ~/go/pkg/mod/github.com/opentofu/hcl/v2@v2.0.0-20240416130056-03228b26f391/hcldec/spec.go:233 +0x330
│ github.com/hashicorp/hcl/v2/hcldec.ObjectSpec.decode(0x14000bbaf60, 0x1400010f620, {0x0, 0x0, 0x0}, 0x14000d09e78)
│       ~/go/pkg/mod/github.com/opentofu/hcl/v2@v2.0.0-20240416130056-03228b26f391/hcldec/spec.go:94 +0x18c
│ github.com/hashicorp/hcl/v2/hcldec.decode({0x104afef78, 0x14000c01d40}, {0x0, 0x0, 0x0}, 0x14000d09e78, {0x104afe488, 0x14000bbaf60}, 0x0)
│       ~/go/pkg/mod/github.com/opentofu/hcl/v2@v2.0.0-20240416130056-03228b26f391/hcldec/decode.go:24 +0x1d8
│ github.com/hashicorp/hcl/v2/hcldec.Decode({0x104afef78, 0x14000c01d40}, {0x104afe488, 0x14000bbaf60}, 0x14000d09e78)
│       ~/go/pkg/mod/github.com/opentofu/hcl/v2@v2.0.0-20240416130056-03228b26f391/hcldec/public.go:18 +0x80
│ github.com/opentofu/opentofu/internal/lang.(*Scope).EvalBlock(0x14000025ef0, {0x104afef78, 0x14000c01d40}, 0x140009ea720)
│       ~/Projects/opentf/internal/lang/eval.go:75 +0x2d0
│ github.com/opentofu/opentofu/internal/tofu.(*BuiltinEvalContext).EvaluateBlock(0x14000ae8200, {0x104afeed0, 0x14000d36870}, 0x140009ea720, {0x0, 0x0}, {{{{0x0, 0x0}}, {0x0, 0x0}}, ...})
│       ~/Projects/opentf/internal/tofu/eval_context_builtin.go:276 +0x1d4
│ github.com/opentofu/opentofu/internal/tofu.(*NodeAbstractResourceInstance).plan(0x140009be400, {0x104b0f8e0, 0x14000ae8200}, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0})
│       ~/Projects/opentf/internal/tofu/node_resource_abstract_instance.go:745 +0x960
│ github.com/opentofu/opentofu/internal/tofu.(*NodePlannableResourceInstance).managedResourceExecute(0x140009c00b0, {0x104b0f8e0, 0x14000ae8200})
│       ~/Projects/opentf/internal/tofu/node_resource_plan_instance.go:284 +0x1a34
│ github.com/opentofu/opentofu/internal/tofu.(*NodePlannableResourceInstance).Execute(0x140009c00b0, {0x104b0f8e0, 0x14000ae8200}, 0x2)
│       ~/Projects/opentf/internal/tofu/node_resource_plan_instance.go:92 +0x100
│ github.com/opentofu/opentofu/internal/tofu.(*ContextGraphWalker).Execute(0x14000ac1680, {0x104b0f8e0, 0x14000ae8200}, {0x12de5c3e8, 0x140009c00b0})
│       ~/Projects/opentf/internal/tofu/graph_walk_context.go:147 +0xd8
│ github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x104a761c0, 0x140009c00b0})
│       ~/Projects/opentf/internal/tofu/graph.go:86 +0x3f8
│ github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0x1400010ef60, {0x104a761c0, 0x140009c00b0}, 0x14000b17240)
│       ~/Projects/opentf/internal/dag/walk.go:385 +0x318
│ created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update in goroutine 123
│       ~/Projects/opentf/internal/dag/walk.go:308 +0xdb4
│ .
╵
```

### Steps to Reproduce

1. `tofu init`
2. `tofu plan`

### References

 - Related issue in the Terraform Repository - https://github.com/hashicorp/terraform/issues/31119

**Comment by cam72cam** [comment] 2024-07-11 14:35
This is a duplicate of #1798

**Closed by cam72cam** 2024-07-11 14:35 UTC
Labels: bug, accepted
