### ISSUE TITLE
Allow 'terraform.workspace' in variable validation

### ISSUE THREAD

**Issue by mm-chia** [opentofu/opentofu#1766] opened 2024-07-02 23:48 UTC
### OpenTofu Version

```shell
OpenTofu v1.8.0-alpha1
on darwin_arm64
+ provider registry.opentofu.org/datadog/datadog v3.39.0
+ provider registry.opentofu.org/hashicorp/aws v5.56.1
+ provider registry.opentofu.org/hashicorp/local v2.5.1
+ provider registry.opentofu.org/hashicorp/null v3.2.2
+ provider registry.opentofu.org/hashicorp/random v3.6.2
+ provider registry.opentofu.org/pagerduty/pagerduty v1.11.0
```

### Use Cases

I would like to allow 'terraform.workspace' to be used in variable validation, for example:

```
variable "environment" {
  type = string

  validation {
    condition     = var.environment == terraform.workspace   # this one does not work
#    condition     = var.environment == "dev"   # -> this one works, but cannot be used because it's hardcoded :)
    error_message = "Variable 'environment' is not matching Terraform workspace!"
  }
}
```

### Attempted Solutions

We could use a 'null_resource' to achieve this, but it's pretty ugly to introduce this resource just for validation purposes:

```
# null_resource used to test if the workspaces matches the environment
resource "null_resource" "test_environment" {
  lifecycle {
    precondition {
      condition     = terraform.workspace == var.environment
      error_message = "Variable 'environment' is not matching Terraform workspace!"
    }
  }
}
```

**Comment by mm-chia** [comment] 2024-07-05 13:07
This would be a very good safety feature, which could prevent applying (through automation) wrong workspace, into wrong environment.
It also goes hand in hand with this feature, which has been already implemented:
https://github.com/opentofu/opentofu/pull/1718
I'd love to see this one implemented as well! It shows that Tofu really cares about community - as opposed to Terraform, where similar features like the one implemented in Tofu, have been ignored for years, and still no plans to implement them :)

**Comment by cam72cam** [comment] 2024-07-10 18:58
Closing as duplicate of https://github.com/opentofu/opentofu/issues/1336.  This comment will link the idea that terraform.workspace should be available when that is implemented.

**Closed by cam72cam** 2024-07-10 18:58 UTC
Labels: enhancement, pending-decision
