### ISSUE TITLE
Getting `context deadline exceeded (Client.Timeout exceeded while awaiting headers)` during `plan`, `apply`

### ISSUE THREAD

**Issue by mirzaprangon** [opentofu/opentofu#1318] opened 2024-02-28 05:50 UTC
### OpenTofu Version

```shell
OpenTofu v1.6.2
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
locals {
  management_cluster = "mc-aws28"
  cluster_sites = {
    "ac-aws28_site-aws28" = {site="site-aws28"}
  }
}

terraform {
  required_providers {
    keycloak = {
      source  = "mrparkers/keycloak"
      version = "4.3.1"
    }
  }
}
resource "keycloak_realm" "site" {
  for_each = local.cluster_sites

  realm                  = each.key
  display_name           = each.key
  reset_password_allowed = true
  verify_email           = true
  remember_me            = true
  ...
}

resource "keycloak_openid_client_scope" "read_cashcards_scope" {
  for_each = local.cluster_sites

  realm_id               = each.key
  name                   = "read:cashcards"
  description            = "Can read cash cards."
  consent_screen_text    = "Can read cash cards"
  include_in_token_scope = true
  gui_order              = 1
  depends_on             = [keycloak_realm.site]
}
...
```

### Debug Output

https://gist.github.com/mirzaprangon/70db2a96b106acc86a5b7ed2133c295c

### Expected Behavior

tofu successfully checks current state and applies any update.

### Actual Behavior

tofu errors out while checking state. The error is something like `Error: error sending request: Get "https://example.com/admin/realms/test": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

### Steps to Reproduce

1. tofu init
2. `tofu plan` or `tofu apply`

### Additional Context

Encountered the error in github codespaces first. Using `mcr.microsoft.com/devcontainers/base:jammy` as the base image.

I tried the same from my local windows machine, which succeeds. Tried devcontainer on local machine, this succeeds too. Encountered problem on Github codespaces and Github actions. I have looked into logs from server side, as far as I understand, the server properly returned the response to the client. But client is saying `context deadline exceeded (Client.Timeout exceeded while awaiting headers)`. Tried terraform, which also gives the same error.

If I set parallelism to 1, I could run `plan` and `apply`. But it will take too much time as there are many resources. The resources are for keycloak if it helps.

**Comment by janosdebugs** [comment] 2024-02-28 06:37
Hi @mirzaprangon , this is likely a bug in the provider you are using. Could you please set the `TF_LOG=debug` environment variable to get a more verbose log? Without exact error messages it's impossible to determine the cause of the error.

**Comment by mirzaprangon** [comment] 2024-02-28 07:07
I should have taken the log using `TF_LOG=trace`, no?
I will take another log, here you go - https://gist.github.com/mirzaprangon/3b9e9f13213159dfd0ae2d937cb8933b

**Comment by janosdebugs** [comment] 2024-02-28 07:37
Hey @mirzaprangon thank you, I specifically didn't ask for trace because it may contain sensitive information. Please check your gist for any secrets that may be included.

**Comment by janosdebugs** [comment] 2024-02-28 07:42
@mirzaprangon I checked your logs and it seems that your KeyCloak isn't responding:

```
2024-02-28T05:26:16.010Z [TRACE] vertex "keycloak_realm.site (expand)": dynamic subgraph encountered errors: error sending request: Get "https://***": context deadline exceeded (Client.Timeout exceeded while awaiting headers),error sending request: Get "https://***": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

This is not a bug in OpenTofu, so I'll close the issue, but feel free to ask for help in the OpenTofu Slack or the GitHub Discussions.

**Closed by janosdebugs** 2024-02-28 07:42 UTC
Labels: bug, pending-decision

**Comment by mirzaprangon** [comment] 2024-02-28 08:36
As I said, I checked the server side log, and server is responding.

And this only occurs when I run in github codespaces, every time. On the other hand, locally it succeeds every time. The server should be fine.

**Comment by janosdebugs** [comment] 2024-02-28 08:47
@mirzaprangon it may be that when you run things in parallel, it isn't working or the server gets overloaded. There may be some tuning you can do on the KeyCloak side. At any rate, this is not something we can fix in OpenTofu, the error is coming from the provider. You may want to take this up with the provider author.

**Comment by mirzaprangon** [comment] 2024-03-04 06:35
After more digging, the problem went away after I changed ingress controller to `traefik`. So, the problem might be in the ingress-nginx. I will open an issue in there.
