### ISSUE TITLE
Flaky unit test nil pointer dereference.

### ISSUE THREAD

**Issue by cube2222** [opentofu/opentofu#1569] opened 2024-04-29 11:37 UTC
https://github.com/opentofu/opentofu/actions/runs/8849246925/job/24300775010

I believe this is again a timing related error in the tests, which is now surfaced by us emulating other architectures using qemu and slowing the tests down significantly doing that.

**Comment by cam72cam** [comment] 2024-04-29 11:38
@cube2222 this is a dupe of https://github.com/opentofu/opentofu/issues/847 and in the future should have a copy of the stack trace.  Run logs are not persisted long term.

**Closed by cam72cam** 2024-04-29 11:38 UTC
