### ISSUE TITLE
Sequential run of tofu init lead to "Backend configuration changed" error

### ISSUE THREAD

**Issue by denis256** [opentofu/opentofu#866] opened 2023-11-13 21:14 UTC
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha4
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "s3" {}
}

```

### Debug Output

https://gist.github.com/denis256/3dccf27af5b832e4f1da4ea903c17dcd

### Expected Behavior

Sequential run of `tofu init` to work without errors

### Actual Behavior

Second run of `tofu init` fail with error

### Steps to Reproduce

1.tofu init -backend-config=bucket=terragrunt-test-bucket-2ttejd -backend-config=encrypt=true -backend-config=key=qwe.tfstate -backend-config=region=us-west-2
2. tofu init -backend-config=bucket=terragrunt-test-bucket-2ttejd -backend-config=encrypt=true -backend-config=key=qwe.tfstate -backend-config=region=us-west-2

### References

https://github.com/hashicorp/terraform/issues/34066

https://github.com/denis256/terragrunt-tests/tree/master/tf-init-error

**Comment by kislerdm** [comment] 2023-11-13 22:18
@denis256 Hey Denis! Thank you for reporting the issue. 

It was already fixed with the following [change](https://github.com/opentofu/opentofu/pull/852). The fix will be part of next release. In the mean time, please consider building `tofu` from source if the issue is blocking you. 

Thank you and stay tuned for upcoming release 😉

**Comment by kislerdm** [comment] 2023-11-14 20:08
@denis256 Hey Denis, I'd like to notify that new version `1.6.0-alpha5` was released today. It includes the fix for this issue. Please update your version of `tofu` (see [how to install](https://opentofu.org/docs/intro/install) for details). Thanks!

**Closed** 2023-11-14 20:09 UTC
Labels: bug, pending-decision
