### ISSUE TITLE
Unclear statements about compatibility with terraform 1.5.x

### ISSUE THREAD

**Issue by gioleppe** [opentofu/opentofu#804] opened 2023-10-31 15:32 UTC
### OpenTofu Version

```shell
(no version here, just website docs)
```

### OpenTofu Configuration Files

```hcl
...tofu config...
```

### Debug Output

no debug

### Expected Behavior

The FAQ should be clear regarding support of statefiles generated by terraform 1.5.x, something along the lines of "There will be no differences between Terraform (versions up to 1.5.x) and OpenTofu. As new versions are released, this will change."
This is especially critical wrt statefiles.

### Actual Behavior

"There will be no differences between Terraform (versions prior to 1.5.x) and OpenTofu. As new versions are released, this will change."

That "prior" keyword is wrong in my opinion, as it suggests 1.5.x versions are not among the ones supported.

### Steps to Reproduce

no steps, just read the docs and the website

**Comment by gioleppe** [comment] 2023-10-31 15:48
I found a PR on the landing page's repository solving this issue, please approve it asap, it greatly adds to clarity :)

https://github.com/opentofu/opentofu.org/pull/197/commits/ccdcf796442d73b260bb056490f01f6a7a38604f

**Comment by serdardalgic** [comment] 2023-10-31 15:57
https://github.com/opentofu/opentofu.org/pull/197 this is the above-mentioned PR

**Comment by kislerdm** [comment] 2023-11-09 07:26
Hey folks! IMO the issue is resolved given that the documentation was updated (see the [PR](https://github.com/opentofu/opentofu.org/pull/197)). WDYT? cc: @Yantrio @serdardalgic @gioleppe

**Comment by Yantrio** [comment] 2023-11-09 11:28
I agree, we can close this.

**Closed by Yantrio** 2023-11-09 11:28 UTC
Labels: bug, accepted
