### ISSUE TITLE
mock_provider enhancements for test framework

### ISSUE THREAD

**Issue by wyardley** [opentofu/opentofu#2013] opened 2024-09-24 02:58 UTC
### OpenTofu Version

```shell
OpenTofu v1.8.2
on darwin_arm64
```

### Use Cases

Support `.tfmock.hcl` and `.tfmock.json` files, and the `source` parameter for `mock_provider` as described in https://developer.hashicorp.com/terraform/language/tests/mocking

This would support easier and more DRY mocking of values, and provide better consistency with terraform.

note: `tf fmt` should obviously also handle updating their formatting.

### Attempted Solutions

```hcl
mock_provider "google" {
  source = "../../../test/fixtures/"
}
```

and in that directory, a file `shared.tfmock.hcl`
```hcl
mock_resource "google_bigquery_dataset" {
  defaults = {
    project = "foo-testproject"
  }
}
```

Gives the error
```
│ Error: Unsupported argument
│ 
│   on tests/main.tftest.hcl line 2, in mock_provider "google":
│    2:   source = "../../../test/fixtures/"
│ 
│ An argument named "source" is not expected here.
```

**Comment by ollevche** [comment] 2024-09-24 09:01
Hello @wyardley and thank you for the issue! We postponed implementing separate files for mocks since we are not sure if that is something community wants. Please, take a look at the #1778 and share your thoughts / use-case!

Closing this as a duplicate of #1778.

**Closed by ollevche** 2024-09-24 09:01 UTC
Labels: enhancement, pending-decision
