### ISSUE TITLE
Add -show-sensitive flag to enable viewing sensitive data in output 

### ISSUE THREAD

**Issue by viktorradnai** [opentofu/opentofu#839] opened 2023-11-08 18:05 UTC
### OpenTofu Version

```shell
Not applicable for feature request.
```

### Use Cases

There are multiple cases where TF knows a sensitive value but refuses to display it, such as:

- viewing TF created secret values
- approving sensitive diffs

While the default behaviour should be to hide secret values, users should be free to decide when to reveal these and should be given the option to do so.

### Attempted Solutions

There are a few workarounds to getting secrets out ot TF, but all of these are painful, especially seeing sensitive diffs for a plan:

1. Run `tofu state pull > state.json` then look through the state file for the secret value
2. Use `output` with `nonsensitive()` to print secret value
3. Save the plan into a file then write a script to make sense of it 

### Proposal

The following commands should accept a `-show-sensitive` flag, and reveal sensitive values when this flag is present:

1. tofu plan -show-sensitive
2. tofu apply -show-sensitive
3. tofu state show kubernetes_secret.foo -show-sensitive
4. tofu output -show-sensitive

**Comment by Yantrio** [comment] 2023-11-09 08:44
Hi Vikktor, 

My personal opinion is that introducing this would undermine the approach to security in general. Whilst I'm not a large fan of 'security through obscurity' I believe that it should not be easy to show sensitive variables and that the secret values should require extra steps to be shown. This saves situations where sensitive properties are accidentally shown.

I'm not 100% against this issue as it's a common problem a lot of us have hit, but I feel like we shouldn't make things easier to leak!

Maybe other people have different opinions, I'd love to hear them.

**Comment by janosdebugs** [comment] 2024-01-29 19:32
Hey @viktorradnai thank you for this issue and sorry for the long delay. We have discussed this issue in the core team and would be happy for a PR to implement this.

If anyone from the community wants to take on this issue, please let us know in the comments so we can assign you. Please note, that given the nature of this change, the PR will only be merged if it is sufficiently covered with tests and makes sure that no secrets are shown unless the appropriate flag is set.

**Comment by yindia** [comment] 2024-02-13 10:38
@janosdebugs could you kindly assign this issue to me? Additionally, I'd appreciate some more details about the changes required.

**Comment by janosdebugs** [comment] 2024-02-13 14:05
Hi @yindia thank you for volunteering, I've assigned this issue to you. Please let us know what your timeline is so we can un-assign this issue and free it up for other community members should we not hear back from you.

**Comment by cam72cam** [comment] 2024-02-15 15:48
So far so good!  This part of the codebase is really repetitive at the moment.

**Comment by ansromanov** [comment] 2024-06-13 10:42
The issue is that `tofu show -json` already shows sensitive values by default, and there is no way to change this behavior at the moment:

```
❯ tofu version                      
OpenTofu v1.7.2
on darwin_arm64

❯ tofu show | grep -i Outputs -A5     
Outputs:

registration_token = (sensitive value)

❯ tg show -json | jq .values.outputs
{

  "registration_token": {
    "sensitive": true,
    "value": "XXXXXXXXXXX",
    "type": "string"
  }
}
```

I propose to make `-show-sensitive` a boolean flag to have the possibility to override such behavior, like `-show-sensitive=false`.
Another possible solution is to hide sensitive data with `tofu show -json` by default, but it could break backward compatibility with Terraform and existing CI pipelines that use `show -json` parameter. 
If it is out of the scope of this feature, I could create a separate issue for this.

**Closed** 2024-07-22 09:58 UTC
Labels: enhancement, help wanted, accepted

**Comment by breml** [comment] 2024-08-16 10:59
If you end up here on the look for a simple way to make sensitive values in a terraform plan visible not only for outputs but also for changed resources, have a look at [tfreveal](https://github.com/breml/tfreveal) a tool I created for exactly this use case.
