### ISSUE TITLE
Re-running `init` with backend-config throws error

### ISSUE THREAD

**Issue by BlueIce** [opentofu/opentofu#2118] opened 2024-10-29 22:12 UTC
### OpenTofu Version

```shell
OpenTofu v1.8.4
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "s3" {
    key = "somekey.tfstate"
  }
}
```

`s3.tfbackend`:
```
bucket = "some-bucket-name"
region = "eu-central-1"
assume_role = {
  role_arn = "XXX"
}
kms_key_id = "XXX"
dynamodb_table = "tf-remote-state-lock"
```

### Debug Output

Log output of second init run:

https://gist.github.com/BlueIce/6d63cc81c958f40628807f250f23eea8

### Expected Behavior

The second run should not throw an error. Both runs should say `OpenTofu has been successfully initalized`.

### Actual Behavior

The first `init` run works fine saying that `OpenTofu has been successfully initalized`.
The second `init` run shows an error saying that the `backend configuration changed`. 
See Gist for detailed output.

### Steps to Reproduce

1. `tofu init -backend-config s3.tfbackend`
2. `tofu init -backend-config s3.tfbackend`

### Additional Context

Version 1.8.3 did not have this behavior.

### References

Could be related to #2024.

**Comment by apparentlymart** [comment] 2024-10-29 22:54
Hello and thank you for this issue! The core team regularly reviews new issues and discusses them, but this can take a little time. Please bear with us while we get to your issue. If you're interested, the contribution guide has a section about the [decision-making process](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#who-decides-if-a-feature-will-be-implemented-and-how-is-that-decision-made).

**Comment by apparentlymart** [comment] 2024-10-29 23:00
I've not yet debugged in detail, but some initial investigation makes me suspect that this is a regression caused by my fix to the earlier bug https://github.com/opentofu/opentofu/issues/2024 .

I changed the code which checks whether the configuration has changed to use the `c.Decode` helper instead of calling `hcldec.Decode` directly, since that was needed to make early eval work in that context: https://github.com/opentofu/opentofu/commit/9e9f6634a1b81373f256033c5713c554efc246d7#diff-54cf37349f548e155ec70c11a597101a0d9e24ec1e58db87cf3bf09088c0f797L1366-R1365

However, I notice that the code was previously passing the decoder spec of a _modified_ schema with nothing marked as required -- `decSpec := schema.NoneRequired().DecoderSpec()` -- which is important to make sure that none of the backend arguments are treated as required until we've merged the `backend` block body with the body of the file given in `-backend-config`. Without that `.NoneRequired()` call this is requiring the `backend` block body to be a complete configuration, regardless of what's included in the `-backend-config` arguments.

If I'm right about this then thankfully the fix seems relatively straightforward: we can use `c.Decode(schema.NoneRequired())` instead of just `c.Decode(schema)`.



Specifically, here:

https://github.com/opentofu/opentofu/commit/9e9f6634a1b81373f256033c5713c554efc246d7#diff-54cf37349f548e155ec70c11a597101a0d9e24ec1e58db87cf3bf09088c0f797L1366-R1365

**Closed** 2024-11-04 19:23 UTC
Labels: bug, accepted
