### ISSUE TITLE
The execution of tofu plan and tofu apply becomes stuck

### ISSUE THREAD

**Issue by askadhum** [opentofu/opentofu#940] opened 2023-11-28 23:50 UTC
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha5
on linux_amd64
```

### OpenTofu Configuration Files

N/A

### Debug Output

```
...
2023-11-29T01:52:23.535+0300 [TRACE] GRPCProvider: Close
2023-11-29T01:52:23.536+0300 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-11-29T01:52:23.574+0300 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.opentofu.org/hashicorp/aws/5.24.0/linux_amd64/terraform-provider-aws pid=32990
2023-11-29T01:52:23.574+0300 [DEBUG] provider: plugin exited
2023-11-29T01:52:23.574+0300 [TRACE] Context.Input: Prompting for provider arguments
2023-11-29T01:52:23.574+0300 [TRACE] Context.Input: Provider provider.aws declared at test1.tf:40,1-15
2023-11-29T01:52:23.574+0300 [TRACE] Context.Input: Input for provider.aws: map[string]cty.Value{}
2023-11-29T01:52:23.575+0300 [TRACE] backend/local: running validation operation
2023-11-29T01:52:23.575+0300 [DEBUG] Building and walking validate graph
2023-11-29T01:52:23.575+0300 [TRACE] building graph for walkValidate
2023-11-29T01:52:23.575+0300 [TRACE] Executing graph transform *tofu.ConfigTransformer
2023-11-29T01:52:23.575+0300 [TRACE] ConfigTransformer: Starting for path:
2023-11-29T01:52:23.575+0300 [TRACE] ConfigTransformer: Starting for path: module.security
2023-11-29T01:52:23.575+0300 [TRACE] ConfigTransformer: Starting for path: module.vpc
2023-11-29T01:52:23.575+0300 [TRACE] Completed graph transform *tofu.ConfigTransformer with new graph:
  aws_instance.web - *tofu.NodeValidatableResource
  module.security.aws_security_group.web-group - *tofu.NodeValidatableResource
  module.security.aws_security_group_rule.web-sg-rule - *tofu.NodeValidatableResource
  module.vpc.aws_internet_gateway.public-gateway - *tofu.NodeValidatableResource
  module.vpc.aws_route_table.public-route-table - *tofu.NodeValidatableResource
  module.vpc.aws_route_table_association.public-route-table-association - *tofu.NodeValidatableResource
  module.vpc.aws_subnet.public-subnet - *tofu.NodeValidatableResource
  module.vpc.aws_vpc.vpc - *tofu.NodeValidatableResource
  ------
2023-11-29T01:52:23.575+0300 [TRACE] Executing graph transform *tofu.RootVariableTransformer
2023-11-29T01:52:23.575+0300 [TRACE] Completed graph transform *tofu.RootVariableTransformer with new graph:
  aws_instance.web - *tofu.NodeValidatableResource
  module.security.aws_security_group.web-group - *tofu.NodeValidatableResource
  module.security.aws_security_group_rule.web-sg-rule - *tofu.NodeValidatableResource
  module.vpc.aws_internet_gateway.public-gateway - *tofu.NodeValidatableResource
  module.vpc.aws_route_table.public-route-table - *tofu.NodeValidatableResource
  module.vpc.aws_route_table_association.public-route-table-association - *tofu.NodeValidatableResource
  module.vpc.aws_subnet.public-subnet - *tofu.NodeValidatableResource
  module.vpc.aws_vpc.vpc - *tofu.NodeValidatableResource
  var.public-ssh-key-path - *tofu.NodeRootVariable
  ------
2023-11-29T01:52:23.575+0300 [TRACE] Executing graph transform *tofu.ModuleVariableTransformer
2023-11-29T01:52:23.575+0300 [TRACE] Completed graph transform *tofu.ModuleVariableTransformer (no changes)
2023-11-29T01:52:23.575+0300 [TRACE] Executing graph transform *tofu.LocalTransformer
2023-11-29T01:52:23.575+0300 [TRACE] Completed graph transform *tofu.LocalTransformer (no changes)
2023-11-29T01:52:23.575+0300 [TRACE] Executing graph transform *tofu.OutputTransformer
2023-11-29T01:52:23.575+0300 [TRACE] OutputTransformer: adding sg-name as *tofu.nodeExpandOutput
2023-11-29T01:52:23.575+0300 [TRACE] OutputTransformer: adding subnet_id as *tofu.nodeExpandOutput
2023-11-29T01:52:23.575+0300 [TRACE] OutputTransformer: adding vpc_id as *tofu.nodeExpandOutput
2023-11-29T01:52:23.575+0300 [TRACE] OutputTransformer: adding publicIP as *tofu.nodeExpandOutput
2023-11-29T01:52:23.575+0300 [TRACE] Completed graph transform *tofu.OutputTransformer with new graph:
  aws_instance.web - *tofu.NodeValidatableResource
  module.security.aws_security_group.web-group - *tofu.NodeValidatableResource
  module.security.aws_security_group_rule.web-sg-rule - *tofu.NodeValidatableResource
  module.security.output.sg-name (expand) - *tofu.nodeExpandOutput
  module.vpc.aws_internet_gateway.public-gateway - *tofu.NodeValidatableResource
  module.vpc.aws_route_table.public-route-table - *tofu.NodeValidatableResource
  module.vpc.aws_route_table_association.public-route-table-association - *tofu.NodeValidatableResource
  module.vpc.aws_subnet.public-subnet - *tofu.NodeValidatableResource
  module.vpc.aws_vpc.vpc - *tofu.NodeValidatableResource
  module.vpc.output.subnet_id (expand) - *tofu.nodeExpandOutput
  module.vpc.output.vpc_id (expand) - *tofu.nodeExpandOutput
  output.publicIP (expand) - *tofu.nodeExpandOutput
  var.public-ssh-key-path - *tofu.NodeRootVariable
  ------
2023-11-29T01:52:23.575+0300 [TRACE] Executing graph transform *tofu.checkTransformer
2023-11-29T01:52:23.575+0300 [TRACE] Completed graph transform *tofu.checkTransformer (no changes)
2023-11-29T01:52:23.575+0300 [TRACE] Executing graph transform *tofu.OrphanResourceInstanceTransformer
2023-11-29T01:52:23.575+0300 [TRACE] Completed graph transform *tofu.OrphanResourceInstanceTransformer (no changes)
2023-11-29T01:52:23.575+0300 [TRACE] Executing graph transform *tofu.StateTransformer
2023-11-29T01:52:23.575+0300 [TRACE] StateTransformer: pointless no-op call, creating no nodes at all
2023-11-29T01:52:23.575+0300 [TRACE] Completed graph transform *tofu.StateTransformer (no changes)
2023-11-29T01:52:23.575+0300 [TRACE] Executing graph transform *tofu.AttachStateTransformer
2023-11-29T01:52:23.575+0300 [TRACE] Completed graph transform *tofu.AttachStateTransformer (no changes)
2023-11-29T01:52:23.575+0300 [TRACE] Executing graph transform *tofu.OrphanOutputTransformer
2023-11-29T01:52:23.575+0300 [TRACE] Completed graph transform *tofu.OrphanOutputTransformer (no changes)
2023-11-29T01:52:23.575+0300 [TRACE] Executing graph transform *tofu.AttachResourceConfigTransformer
...
```

### Expected Behavior

I getting below error when running `terraform plan`

```
 Error: configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
 
 Please see https://registry.terraform.io/providers/hashicorp/aws
 for more information about providing credentials.
 
 AWS Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, http response error StatusCode: 404, request to EC2 IMDS failed
 
 
   with provider["registry.terraform.io/hashicorp/aws"],
   on main.tf line 4, in provider "aws":
    4: provider "aws" {
```

### Actual Behavior

When AWS credentials are undefined, running `tofu plan` or `tofu apply` getting stuck.

### Steps to Reproduce

1. `tofu init`
2. `tofu plan` or `tofu apply`

**Comment by janosdebugs** [comment] 2023-11-29 06:44
Hey @askadhum please post your TF config files, without them it will be difficult to track down this issue. Also, please post the entire debug output, not just the last part.

**Comment by cam72cam** [comment] 2023-11-29 15:42
Given the information provided, I tried messing with the `ec2_metadata_service_endpoint` and was unable to reproduce the issue.  This is blocked waiting on more information from the submitter.

**Comment by askadhum** [comment] 2023-11-29 18:11
Dear @janosdebugs, You can experiment with [these](git clone https://github.com/hashicorp/learn-terraform-provision-eks-cluster) configurations. Simply comment out the cloud block in the `terraform.tf` file. 
For debug logs, please refer to the attached file. 
[plan.txt](https://github.com/opentofu/opentofu/files/13504101/plan.txt)

**Comment by janosdebugs** [comment] 2023-11-29 18:49
@askadhum have you, as the tutorial asks, installed and configured the AWS CLI with your credentials? The error message complains about missing credentials, which is the case if the CLI configuration is missing. The AWS provider fetches its configuration from the CLI configuration unless otherwise specified. (Which is not the case with this example code.)

**Comment by askadhum** [comment] 2023-11-29 23:16
@janosdebugs Nope, in the both tests (using `terraform` and `tofu`) the AWS CLI is not installed at all, and I was intentional in not using it (in order to check the behaviors of `tofu`)

**Comment by janosdebugs** [comment] 2023-11-29 23:27
Please follow the instructions in the tutorial and use tofu instead of terraform. Tofu cannot magically do parts of the tutorial that you are supposed to do. Closing this issue as this is not a bug.

**Closed** 2023-11-29 23:28 UTC
Labels: invalid

**Comment by askadhum** [comment] 2023-11-29 23:33
@janosdebugs my question for you is, when i use terraform, I'm getting and error message that says 

>  Error: configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.

While with tofu its just don't show anything, can you clarify this point for me?
