### ISSUE TITLE
Encryption: unable to set parameters via TF_ENCRYPTION

### ISSUE THREAD

**Issue by 111a5ab1** [opentofu/opentofu#1642] opened 2024-05-11 14:11 UTC
### OpenTofu Version

```shell
OpenTofu v1.7.1
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
terraform {
  encryption {
    key_provider "pbkdf2" "main" {
    }

    method "aes_gcm" "main" {
      keys = key_provider.pbkdf2.main
    }

    state {
      enforced = true
      method   = method.aes_gcm.main
    }

    plan {
      enforced = true
      method   = method.aes_gcm.main
    }
  }
}

locals {
  foo = "bar"
}
```

### Debug Output

[TF_LOG=trace tofu apply](https://gist.github.com/111a5ab1/6c6af11eb8f174ca91dca534e944d6f9)

### Expected Behavior

`TF_ENCRYPTION` environment variable settings are merged into OpenToFu state encryption settings in `main.tf`.

### Actual Behavior

`tofu apply` fails with:
```
╷
│ Error: Unsupported block type
│ 
│   on TF_ENCRYPTION line 1:
│   (source code not available)
│ 
│ Blocks of type "terraform" are not expected here.
```

### Steps to Reproduce

1. Export `TF_ENCRYPTION` variable settings:
```
$ export TF_ENCRYPTION=$(cat <<EOF
terraform {
  encryption {
    key_provider "pbkdf2" "main" {
      passphrase = "correct-horse-battery-staple"
    }
  }
}
EOF
)
```
2. Confirm variable set:
```
$ printf "${TF_ENCRYPTION}\n"
terraform {
  encryption {
    key_provider "pbkdf2" "main" {
      passphrase = "correct-horse-battery-staple"
    }
  }
}
```
3. `tofu apply`

### Additional Context

Setting the passphrase directly in `main.tf` works as expected:

```hcl
terraform {
  encryption {
    key_provider "pbkdf2" "main" {
      passphrase = "correct-horse-battery-staple"
    }
...
```

```
$ unset TF_ENCRYPTION
$ tofu apply
No changes. Your infrastructure matches the configuration.

OpenTofu has compared your real infrastructure against
your configuration and found no differences, so no
changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by cam72cam** [comment] 2024-05-11 15:42
The encryption env var does not need the terraform block, just the nested encryption block

**Comment by 111a5ab1** [comment] 2024-05-11 22:44
Hi @cam72cam, thanks for your reply.

The [Environment (Linux/UNIX shell)](https://opentofu.org/docs/language/state/encryption/#configuration) configuration example in the OpenToFu documents has the full `terraform` block--which is what I used as reference.

I forgot to mention that I did try removing the `terraform` block and various iterations:
```
export TF_ENCRYPTION=$(cat <<EOF
encryption {
  key_provider "pbkdf2" "main" {
    passphrase = "correct-horse-battery-staple"
  }
}
EOF
)
```

Which then resulted in it complaining about the `encryption` block:
```
╷
│ Error: Unsupported block type
│ 
│   on TF_ENCRYPTION line 1:
│   (source code not available)
│ 
│ Blocks of type "encryption" are not expected here.
╵
```

So I also tried just setting the `key_provider` block (which matches the format shown for [`TF_ENVIRONMENT`](https://opentofu.org/docs/cli/config/environment-variables/#tf_encryption) in the Environment Variables section of the documentation):
```
export TF_ENCRYPTION=$(cat <<EOF
key_provider "pbkdf2" "main" {
  passphrase = "correct-horse-battery-staple"
}
EOF
)
```

This results in:
```
╷
│ Error: Missing required argument
│ 
│   on main.tf line 3, in terraform:
│    3:     key_provider "pbkdf2" "main" {
│ 
│ The argument "passphrase" is required, but no definition was
│ found.
```

I'm not a Go person, but I was also trying quickly late last night (unsuccessfully) to have a look through the source code to try to identify the correct syntax.

**Comment by cam72cam** [comment] 2024-05-12 00:19
Ok, our documentation is definitely wrong then.  We will update that early next week.

**Comment by cam72cam** [comment] 2024-05-12 00:21
It looks like the config merge between the environment and the cfg file is not working as intended.  I'll dig into that.

I removed the empty key_provider block in your example with the correct env var and it worked.

**Comment by cam72cam** [comment] 2024-05-12 00:42
Looks like it's a misunderstanding I had when using hcl2shim.MergeBodies.

**Comment by 111a5ab1** [comment] 2024-05-12 03:43
> I removed the empty key_provider block in your example with the correct env var and it worked.

Ah ta, that did the trick:
```hcl
terraform {
  encryption {
    #key_provider "pbkdf2" "main" { <- whole block must be set via env var only 
    #}

    method "aes_gcm" "main" {
      keys = key_provider.pbkdf2.main
    }

...
```

```bash
$ echo "${TF_ENCRYPTION}"
key_provider "pbkdf2" "main" {
  passphrase = "correct-horse-battery-staple"
}

$ tofu apply
No changes. Your infrastructure matches the configuration.

OpenTofu has compared your real infrastructure against your
configuration and found no differences, so no changes are
needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by 111a5ab1** [comment] 2024-05-12 04:46
@cam72cam I've opened #1644 to hopefully clarify the above in the docs.

**Comment by cam72cam** [comment] 2024-06-05 11:59
Fixed by https://github.com/opentofu/opentofu/pull/1670

**Closed by cam72cam** 2024-06-05 11:59 UTC
Labels: bug, pending-decision
