### ISSUE TITLE
Local state update precedence deviates in apply vs console failing to render result

### ISSUE THREAD

**Issue by sempervictus** [opentofu/opentofu#1999] opened 2024-09-19 15:34 UTC
### OpenTofu Version

```shell
OpenTofu v1.8.2
```

### OpenTofu Configuration Files

```hcl
  test_1_subnet_member_map = {
    for d in coalesce(distinct(flatten(([
      for machine in local.test_1_machines: [
        for subnet in data.provider_subnet.test-1: [
          for addr in subnet.ip_addresses: {
            hostname = machine.hostname
            fqdn     = addr.fqdn
            machine  = machine.id
            ip       = addr.ip
            cidr     = subnet.cidr
            vlan     = subnet.vid
          } if "${addr.fqdn}" == "${machine.hostname}.${machine.domain}"
        ]
      ]
    ])))): d.machine => d... if d.vlan != null
  }
```

### Debug Output

https://gist.github.com/sempervictus/4bf6bd83b64a006d1b17df38db74a1a2

### Expected Behavior

The `local` should be the same in the `plan` and `apply` contexts as it is in the console. The `local` is composed of nested data and resource dependencies which appear to be not pulled-in during those verbs but for some reason correctly resolved in `console` context. Tofu is somehow not understanding the dependency structure and attempting to index into the `local` map before having updated it with the newly added third key.

### Actual Behavior

```
╷
│ Error: Invalid index
│ 
│   on cluster-test-1.tf line 96, in locals:
│   96:     for machine in local.test_1_machines: machine.id => local.test_1_subnet_member_map[machine.id][0].ip 
│     ├────────────────
│     │ local.test_1_subnet_member_map is object with 2 attributes
│     │ machine.id is "sthr6x"
│ 
│ The given key does not identify an element in this collection value.
```
where as `$ tofu console` gives us
```hcl
> length(keys(local.test_1_subnet_member_map))
3
```
and allows indexing the map by the `machine.id` in the error.

### Steps to Reproduce

1. apply configuration
2. update `local.machines` which expands other locals/data/resources (such as `local.test_1_machines`) causing `local.test_1_subnet_member_map` to be indexed for the added value to `local.machines` (it contains the relevant key in `tofu console`)
3. apply again and watch data and resources be correctly indexed for the key but fail when indexing into the subordinate (several levels down) `local.test_1_subnet_member_map`

**Comment by apparentlymart** [comment] 2024-10-02 22:18
I'm not 100% sure from the context given but I think the most likely cause of this discrepancy is that `tofu plan` evaluates expressions based on earlier-added entries of the plan currently being created, while `tofu console` evaluates expressions based only on the prior state.

In the "creating from nothing" case, where there's a `resource` or `data` block in the configuration that hasn't yet been present through a plan/apply round, `tofu console` treats the entire object representing that resource as an unknown value. In the given example that would mean that `data.provider_subnet.test-1`'s elements are all unknown values of whatever object type is described by the provider's schema for this resource type.

However, by the time `tofu plan` is visiting this local value the language runtime would already have visited and evaluated the configuration for `data.provider_subnet.test-1`, and so its value would now be a _known_ object-typed value, though some of its leaf attribute values might still be unknown individually unless the data source configuration was complete enough to read it during the plan phase.

The Tofu language's evaluation model has a general opinion that applies here: if an unknown value means that it's impossible to decide whether or not something is valid, Tofu will optimistically assume that it is valid to allow progress to the next step and then check again once it has more information. Tofu will report an error in the earliest phase where there's enough information to decide it, but typically won't pessimistically reject an expression that _might_ be invalid.

I think that's ultimately what's happening here: in the initial evaluation in `tofu console` perhaps `machine.id` or `local.test_1_subnet_member_map` aren't known yet, and so the expression evaluator just makes the overall expression return some sort of place holder like a map of unknown values. The keys of that map are known and so it has enough information to conclude that it has length three, and so it returns that information.

However, by the time this expression gets evaluated during `tofu plan` the language runtime clearly _does_ know exactly what `machine.id` and `local.test_1_subnet_member_map` are (as described in the error message) and so there's now enough information to definitively conclude that this expression is invalid.

If my assumptions about root cause are correct here then unfortunately I think this describes OpenTofu working as intended. However, if you have more information that suggests that I'm making an incorrect assumption, please let me know! I'd love to reconsider this with more information available.

**Comment by cam72cam** [comment] 2024-11-05 16:30
Closing as this is expected functionality.  Feel free to ping us to re-open the issue.

**Closed by cam72cam** 2024-11-05 16:30 UTC
Labels: bug, pending-decision
