### ISSUE TITLE
Planable import get unexpected update action when import resource with sensitive path

### ISSUE THREAD

**Issue by chenzejun** [opentofu/opentofu#1231] opened 2024-02-05 02:45 UTC
### OpenTofu Version

```shell
-> % tofu -version 
OpenTofu v1.7.0-dev
```

### OpenTofu Configuration Files

```
data "kubernetes_namespace" "ns" {
  metadata {
    name = "namespace-test"
  }
}

data "kubernetes_secret" "src" {
  metadata {
    name      = "secret-src"
    namespace = data.kubernetes_namespace.ns.id
  }
}

resource "kubernetes_secret" "dst" {
  metadata {
    name      = "secret-dst"
    namespace = data.kubernetes_namespace.ns.id
  }
  wait_for_service_account_token = false
  type                           = "kubernetes.io/basic-auth"
  data = data.kubernetes_secret.src.data
}

import {
  to = kubernetes_secret.dst
  id = "namespace-test/secret-dst"
}

```

### Expected Behavior

Plan: 1 to import, 0 to add, 0 to change, 0 to destroy.

### Actual Behavior

![image](https://github.com/opentofu/opentofu/assets/26278304/87f28e5f-8226-40d3-8818-f684fa5dfa4b)

### Steps to Reproduce

tofu init
prepare two secret with same value
tofu plan

### Additional Context

the bug may be caused here:
https://github.com/opentofu/opentofu/blob/199ec898e634b5c2782664cf436bac94eae3fd10/internal/tofu/node_resource_abstract_instance.go#L1087C1-L1096C1

**Comment by RLRabinowitz** [comment] 2024-02-05 12:46
Hey there @chenzejun !

I was able to reproduce this issue specifically with your setup. Doesn't seem to be specifically related to importing secret values, as I could not reproduce this with a different resource importing a secret value to it.

I will try to see what the cause of the issue is

**Comment by RLRabinowitz** [comment] 2024-02-05 14:48
So it seems like the issue indeed stems from an issue with how marks are evaluated.
I will accept this issue.

**Comment by chenzejun** [comment] 2024-03-07 12:24
Hello @RLRabinowitz I have some ideas to fix it, can you sssign it to me?

**Comment by RLRabinowitz** [comment] 2024-03-07 15:37
Hey @chenzejun , sure I will assign you this issue.

This issue is indeed something that we would like to push forward, as we've marked it as part of the milestone for 1.7.0 release.

**Comment by chenzejun** [comment] 2024-03-08 07:47
Hey @RLRabinowitz! PTAL on my PR https://github.com/opentofu/opentofu/pull/1350

**Closed** 2024-03-28 15:19 UTC
Labels: bug, accepted
