### ISSUE TITLE
Add higher level of abstraction to the language

### ISSUE THREAD

**Issue by tofkamp** [opentofu/opentofu#761] opened 2023-10-20 10:18 UTC
### OpenTofu Version

```shell
The latest.. doesn't matter
```

### Use Cases

In larger enviroment like enterprises.

### Attempted Solutions

define "macroname" {
input = { var.x, y,z}
output = { }
resources = {
resource "x" { ... var.x ..}
}

macroname "production deployemnt" {
  x = 5
  z = "hello"
}

macroname "test deployemnt" {
  x = 1
  z = "hello"
}

### Proposal

I am using terraform providers and modules to manage al my mikrotik switches. The problem with the current language is that there is no abstraction possible. It is not easy to separate the definition and the instantiation of an environment. When the number of resources increase the more lowlevel work (and errors) will be done.
It would be good to create classes (like python/java), with methods' and inheritance etc, like a modern language. And then use those classes to instantiate multiple environments with resources.
Add more abstraction to the language. This will defer from the terraform version, and create an incompatible language from opentofu back to terraform, but it will be much easier to create and manage larger environments. It is a choice, what to do with this product? Expand the possibilities, or stay loyal to the current version?

Remarkable: The code is written in golang, but the most basic object handling is not implemented in HCL.

### References

I did not find any, but there could be others also experience the same struggle with the simple language in larger enviroments.

**Comment by kislerdm** [comment] 2023-10-20 11:38
Hey! Thanks for the proposal, limitations of HCL are widely acknowledged, however I think that we shall be mindful about the tradeoffs when considering steps towards paradigm change - imperative vs. declarative. 

Have you tried [workspaces](https://opentofu.org/docs/language/state/workspaces/)? I feel that it may help to solve your problem.

**Comment by cube2222** [comment] 2023-10-20 13:16
> It would be good to create classes (like python/java), with methods' and inheritance etc, like a modern language. And then use those classes to instantiate multiple environments with resources.
Add more abstraction to the language. This will defer from the terraform version, and create an incompatible language from opentofu back to terraform, but it will be much easier to create and manage larger environments. It is a choice, what to do with this product? Expand the possibilities, or stay loyal to the current version?

Seems to me like [Pulumi](https://www.pulumi.com) fits the requirements you've described here.

I don't think it'd make sense to move OpenTofu in the direction of general purpose programming languages, a lot of people prefer the constrained DSL - it's a tradeoff.

**Comment by Magnitus-** [comment] 2023-10-20 13:30
I've encountered very few real limitations with HCL (mostly with the parts that were exception to the regular flow like module sources or provider blocks that have to be constants and can't be configured with values read from files for example).

You can use modules for a lot of the reusability use-cases and when you need more flexibility, a custom provider will do the job, but will make you implement your user-facing interface in a way that is far less likely to break the declarative contract with your end-user.

Combined with the declarative nature of HCL, you can create a platform that is usable by people who are not necessarily natural-born programmers with far fewer ways to shoot themselves in the foot.

Last thing I want is an obscure bug in a database cluster caused by 4 layers of inheritance.

**Comment by schollii** [comment] 2023-10-29 19:01
This proposal is far too vague and open ended. Eg modules together with type-constrained inputs and outputs provide a good level of abstraction for re-usability and strong typing. Outline a specific limitation that is not covered by the above, and a specific solution.

**Comment by janosdebugs** [comment] 2024-01-29 19:02
Hey folks, thank you so much for the input and apologies for the late response. We have discussed this issue in the core team and feel like this feature would be a significant departure from the language as it currently exists. It would require a large-scale change to the OpenTofu codebase and fundamentally break the compatibility with Terraform. Furthermore, it would require us to maintain a significantly changed fork of the HCL language and its related libraries. As such, this is not something we currently have the capacity for and will be closing the issue. We would recommend Pulumi for these use cases.

**Closed by janosdebugs** 2024-01-29 19:02 UTC
Labels: enhancement, pending-decision
