### ISSUE TITLE
Expose opentofu as a library to allow integration in other programs

### ISSUE THREAD

**Issue by takeda** [opentofu/opentofu#758] opened 2023-10-19 19:06 UTC
### OpenTofu Version

So opentofu is currently a standalone program based on TF. In many cases standalone use works as it can be called from CI/CD pipeline.

In some scenarios there's a need to integrate opentofu into application. There's supposedly something that does it called terraform-exec but it suffers from 2 issues:

1. it only works with Go code, doesn't work with other programs
2. it is just a wrapper around CLI, not an actual library

What this ticket is hoping for is a C-compatible library (which can then have wrapper in other languages) that can be integrated into code. For example https://stackoverflow.com/a/32217287

This feature could be a great differentiator from the original product, as being exposed as a library might go a bit against their business model. The existence of terraform-exec shows that there's interest in integrating TF within code, but as I mentioned earlier, this has plenty of issues.

### Use Cases

Writing services that dynamically set up and change infrastructure.

### Attempted Solutions

- using CloudFormation (the deployment happens on AWS side)
- bundling terraform and wrapping CLI (possible, but this creates a lot of issues)

### Proposal

Expose opentofu operations as a C library

**Comment by kislerdm** [comment] 2023-10-20 12:18
Hey, thanks for the request! Indeed, I feel that it may be beneficial to provide OpenTofu as a Go module. However, development C library would deviate from the OpenTofu objectives IMO.

**Comment by OleksandrUA** [comment] 2023-10-20 12:35
Exposing OpenTofu as a C library sounds like step 2 for me. I agree with @kislerdm - providing OpenTofu as a Go module looks a) more feasible at this moment b) but still solving the problem you have raised. I would like to double the problem you raised - I had to develop CLI wrappers around terraform binaries which is quite ugly and requires too much additional efforts.

**Comment by cube2222** [comment] 2023-10-20 13:11
Also related to #544

Generally, this would have to be thought through very well. I don't think the point is to just expose plan/apply as a library, cause when using it as a library you might want to do create/update/destroy on resources/modules?

Seems to me like the closest thing to this would be the [Pulumi Automation API](https://www.pulumi.com/docs/using-pulumi/automation-api/).

**Comment by takeda** [comment] 2023-10-20 16:49
> Seems to me like the closest thing to this, conceptually, would be the [Pulumi Automation API](https://www.pulumi.com/docs/using-pulumi/automation-api/).

I actually tried it, and turns out that their solution on the surface looks great, but internally they still have an executable that this API is calling.

> Also, iirc you'd still need to bundle the providers, which are external plugins. So I'm not sure if there's that much to be gained over what terraform-exec does (as long as only a plan/apply API is wanted).

That isn't as much problem with solutions like Nix I can just do something like: `terraform.withPlugins (p: [ p.aws p.hcloud ])` and everything I need will be included with my application.

**Comment by zhenrong-wang** [comment] 2023-11-30 15:18
I developed my project HPC-NOW purely in C. And I use system call in C to run tf (both terraform and openTofu). It turns out to work well. 

Is a C library really necessary? I am not sure.

**Comment by takeda** [comment] 2023-12-05 05:46
I also have a python code that wraps terraform, in a similar way, but it feels hacky.

**Comment by zhenrong-wang** [comment] 2023-12-05 11:32
> I also have a python code that wraps terraform, in a similar way, but it feels hacky. By exposing opentofu as a C library one could integrate it better.

I think it depends on how complicated the integration is. If just run the basic commands such as plan, apply, destroy, or use these basic functions, it seems to be acceptable to wrap the binary executable up with some simple data structures. An simple example, in C, we can use a `struct tofu_config { }` to wrap all the tf running configurations and then run `system("tofu")` .

However, if one wants to integrate the advanced features, for sure a library would be much helpful.

**Comment by cube2222** [comment] 2024-01-22 15:30
Closing as duplicate of https://github.com/opentofu/opentofu/issues/544.

**Closed by cube2222** 2024-01-22 15:30 UTC
Labels: enhancement, pending-decision
